server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
    context-path: '/'

spring:
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${DB_URL:dpg-cnh4qqnsc6pc73dtoqc0-a.oregon-postgres.render.com}:${DB_PORT:5432}/${DB_NAME:desafio_java}
    username: ${DB_USERNAME:desafio_java_user}
    password: ${DB_PASSWORD:yTNXdM5c8ry3bqqVz29qUkMbxiv70a3w}
    connectionTestQuery: 'SELECT 1'
  flyway:
    enabled: false
    user: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: validate
    generate-ddl: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always